[package]
name = "from-junior-to-senior"
version = "0.1.0"
authors = ["Daniil Kolesnichenko <d.s.kolesnichenko@yandex.ru>"]

[dependencies]
clap = "2.30"
mustache = "*"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"